# Generated by Django 2.1.15 on 2021-06-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='storeCode',
            field=models.IntegerField(db_column='StoreCode', max_length=30),
        ),
    ]
