# Generated by Django 2.1.15 on 2021-06-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210617_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='storeCode',
            field=models.IntegerField(db_column='StoreCode'),
        ),
    ]
