# Generated by Django 2.2 on 2021-06-18 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210617_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryId', models.IntegerField(db_column='CategoryId', primary_key=True, serialize=False)),
                ('category_name', models.CharField(db_column='Name', max_length=100)),
                ('description', models.CharField(db_column='Description', max_length=100, null=True)),
                ('rackNumber', models.IntegerField(db_column='RackNumber', null=True)),
                ('fromDate', models.DateField(db_column='FromDate', null=True)),
                ('thruDate', models.DateField(db_column='ThruDate', null=True)),
                ('creator', models.CharField(db_column='Creator', max_length=30, null=True)),
                ('created', models.DateField(db_column='Created', null=True)),
                ('modifier', models.CharField(db_column='Modifier', max_length=30, null=True)),
                ('modified', models.DateField(db_column='Modified', null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='store',
            name='created',
            field=models.DateField(db_column='Created', null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='creator',
            field=models.CharField(db_column='Creator', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='fromDate',
            field=models.DateField(db_column='FromDate', null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='modified',
            field=models.DateField(db_column='Modified', null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='modifier',
            field=models.CharField(db_column='Modifier', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='postalcode',
            field=models.CharField(db_column='Postalcode', max_length=7),
        ),
        migrations.AlterField(
            model_name='store',
            name='secondaryContact',
            field=models.CharField(db_column='SecondaryContact', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='storeRefId',
            field=models.CharField(db_column='StoreRefId', max_length=20),
        ),
        migrations.AlterField(
            model_name='store',
            name='thruDate',
            field=models.DateField(db_column='ThruDate', null=True),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.IntegerField(db_column='ProductId', primary_key=True, serialize=False)),
                ('product_name', models.CharField(db_column='Name', max_length=100)),
                ('description', models.CharField(db_column='Description', max_length=500, null=True)),
                ('quantity', models.IntegerField(db_column='Quantity', null=True)),
                ('price', models.DecimalField(db_column='Price', decimal_places=2, max_digits=5, null=True)),
                ('discount', models.DecimalField(db_column='Discount', decimal_places=2, max_digits=3, null=True)),
                ('company', models.CharField(db_column='Company', max_length=100, null=True)),
                ('ingredients', models.CharField(db_column='Ingredients', max_length=500, null=True)),
                ('fromDate', models.DateField(db_column='FromDate', null=True)),
                ('thruDate', models.DateField(db_column='ThruDate', null=True)),
                ('creator', models.CharField(db_column='Creator', max_length=30, null=True)),
                ('created', models.DateField(db_column='Created', null=True)),
                ('modifier', models.CharField(db_column='Modifier', max_length=30, null=True)),
                ('modified', models.DateField(db_column='Modified', null=True)),
                ('CategoryId', models.ForeignKey(db_column='CategoryId', on_delete=django.db.models.deletion.CASCADE, to='core.Category')),
                ('storeId', models.ForeignKey(db_column='StoreId', on_delete=django.db.models.deletion.CASCADE, to='core.Store')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='storeId',
            field=models.ForeignKey(db_column='StoreId', on_delete=django.db.models.deletion.CASCADE, to='core.Store'),
        ),
    ]
