# Generated by Django 2.2 on 2021-07-01 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210618_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categoryId',
            field=models.AutoField(auto_created=True, db_column='CategoryId', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='productId',
            field=models.AutoField(auto_created=True, db_column='ProductId', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='store',
            name='storeId',
            field=models.AutoField(auto_created=True, db_column='StoreId', primary_key=True, serialize=False),
        ),
    ]
