# Generated by Django 2.2 on 2021-07-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210701_0754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='CategoryId',
            new_name='categoryId',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(db_column='Price', decimal_places=2, max_digits=7, null=True),
        ),
    ]
