# Generated by Django 2.2 on 2021-07-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210701_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='firstname',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='lastname',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
