# Generated by Django 2.2 on 2021-07-06 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210704_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.IntegerField(db_column='ProductId')),
                ('storeId', models.IntegerField(db_column='StoreId')),
                ('orderId', models.IntegerField(db_column='OrderId')),
                ('quantity', models.IntegerField(db_column='Quantity')),
                ('amount', models.DecimalField(db_column='Amount', decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.AddField(
            model_name='owner',
            name='allergicIngredients',
            field=models.CharField(db_column='AllergicIngredients', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='contact',
            field=models.CharField(blank=True, db_column='CustomerContact', max_length=12),
        ),
        migrations.AddField(
            model_name='owner',
            name='is_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderId', models.AutoField(db_column='OrderId', primary_key=True, serialize=False)),
                ('orderDate', models.DateTimeField(db_column='OrderDate')),
                ('orderType', models.CharField(choices=[('M', 'Multiple'), ('S', 'Single')], db_column='OrderType', max_length=15, null=True)),
                ('OrderAmount', models.DecimalField(db_column='OrderAmount', decimal_places=2, max_digits=7)),
                ('status', models.CharField(choices=[('A', 'Approved'), ('R', 'Ready'), ('P', 'Preparing'), ('C', 'Cancelled'), ('D', 'Disapproved')], db_column='OrderStatus', max_length=15, null=True)),
                ('paid', models.BooleanField(db_column='IsPaid', default=False)),
                ('fromDate', models.DateField(db_column='FromDate', null=True)),
                ('thruDate', models.DateField(db_column='ThruDate', null=True)),
                ('creator', models.CharField(db_column='Creator', max_length=30, null=True)),
                ('created', models.DateField(db_column='Created', null=True)),
                ('modifier', models.CharField(db_column='Modifier', max_length=30, null=True)),
                ('modified', models.DateField(db_column='Modified', null=True)),
                ('customerId', models.ForeignKey(db_column='CustomerId', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
