# Generated by Django 2.2 on 2021-07-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210706_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('imageId', models.AutoField(auto_created=True, db_column='ImageId', primary_key=True, serialize=False)),
                ('imagePath', models.ImageField(upload_to='images')),
            ],
        ),
    ]
