# Generated by Django 2.2 on 2021-08-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='productId',
            field=models.IntegerField(db_column='productId', null=True),
        ),
    ]
