# Generated by Django 2.2 on 2021-08-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210807_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='firstname',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='lastname',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
